SELECT DISTINCT
X.NUM_PED "num_ped",
X.ITPDV_ID "itpdv_id",
X.TIPO "tipo",
X.PAI "pai",
X.FILHO "filho",
X.DESC_PAI "desc_pai",
X.DESC_FILHO "desc_filho"
FROM
( 
SELECT
TPEDIDOS_VENDA.NUM_PEDIDO "NUM_PED",
TITENS_PDV.ID "ITPDV_ID",
TCONFIG_ITENS.SEQ "SEQ",
TCONJUNTOS.ID "TIPO",

TVARIAVEIS.DESCRICAO "PAI",
(SELECT LISTAGG(TVARIAVEIS2.DESCRICAO) WITHIN GROUP (ORDER BY TVARIAVEIS2.DESCRICAO)
FROM focco3i.TCONFIG_ITENS TCONFIG_ITENS2
JOIN focco3i.TCARACTERISTICAS TCARACTERISTICAS2 ON TCARACTERISTICAS2.ID = TCONFIG_ITENS2.TCARAC_ID AND TCARACTERISTICAS2.TCONJ_ID NOT IN (963,980)
JOIN focco3i.TVARIAVEIS TVARIAVEIS2 ON TVARIAVEIS2.ID = TCONFIG_ITENS2.TVAR_ID
LEFT JOIN focco3i.TVARIAVEIS_IDIOMAS TVARIAVEIS_IDIOMAS2 ON TVARIAVEIS_IDIOMAS2.TVAR_ID = TVARIAVEIS2.ID AND TVARIAVEIS_IDIOMAS2.IDIOMAS_ID = TIDIOMAS_VAR.ID
JOIN focco3i.TITENS_CAR TITENS_CAR2 ON TITENS_CAR2.ITEMPR_ID = TCONFIG_ITENS2.ITEMPR_ID AND TITENS_CAR2.TCARAC_ID = TCARACTERISTICAS2.ID
WHERE TCONFIG_ITENS2.TMASC_ITEM_ID = TCONFIG_ITENS.TMASC_ITEM_ID 
AND TITENS_CAR2.TITEM_CAR_ID = TITENS_CAR.ID) "FILHO",

COALESCE(TVARIAVEIS_IDIOMAS.DESCRICAO,TVARIAVEIS.DESCRICAO) "DESC_PAI",
(SELECT LISTAGG(COALESCE(TVARIAVEIS_IDIOMAS2.DESCRICAO,TVARIAVEIS2.DESCRICAO)) WITHIN GROUP (ORDER BY COALESCE(TVARIAVEIS_IDIOMAS2.DESCRICAO,TVARIAVEIS2.DESCRICAO))
FROM focco3i.TCONFIG_ITENS TCONFIG_ITENS2
JOIN focco3i.TCARACTERISTICAS TCARACTERISTICAS2 ON TCARACTERISTICAS2.ID = TCONFIG_ITENS2.TCARAC_ID AND TCARACTERISTICAS2.TCONJ_ID NOT IN (963,980)
JOIN focco3i.TVARIAVEIS TVARIAVEIS2 ON TVARIAVEIS2.ID = TCONFIG_ITENS2.TVAR_ID
LEFT JOIN focco3i.TVARIAVEIS_IDIOMAS TVARIAVEIS_IDIOMAS2 ON TVARIAVEIS_IDIOMAS2.TVAR_ID = TVARIAVEIS2.ID AND TVARIAVEIS_IDIOMAS2.IDIOMAS_ID = TIDIOMAS_VAR.ID
JOIN focco3i.TITENS_CAR TITENS_CAR2 ON TITENS_CAR2.ITEMPR_ID = TCONFIG_ITENS2.ITEMPR_ID AND TITENS_CAR2.TCARAC_ID = TCARACTERISTICAS2.ID
WHERE TCONFIG_ITENS2.TMASC_ITEM_ID = TCONFIG_ITENS.TMASC_ITEM_ID 
AND TITENS_CAR2.TITEM_CAR_ID = TITENS_CAR.ID) "DESC_FILHO"

FROM focco3i.TITENS_PDV

JOIN focco3i.TPEDIDOS_VENDA ON TPEDIDOS_VENDA.ID = TITENS_PDV.PDV_ID
JOIN focco3i.TITENS_COMERCIAL ON TITENS_COMERCIAL.ID = TITENS_PDV.ITCM_ID
JOIN focco3i.TITENS_EMPR ON TITENS_EMPR.ID = TITENS_COMERCIAL.ITEMPR_ID
JOIN focco3i.TMASC_ITEM ON TMASC_ITEM.ID = TITENS_PDV.TMASC_ITEM_ID
JOIN focco3i.TCONFIG_ITENS ON TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID
JOIN focco3i.TCARACTERISTICAS ON TCARACTERISTICAS.ID = TCONFIG_ITENS.TCARAC_ID AND TCARACTERISTICAS.TCONJ_ID IN (963,980)
JOIN focco3i.TCONJUNTOS ON TCONJUNTOS.ID = TCARACTERISTICAS.TCONJ_ID
JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID
JOIN focco3i.TITENS_CAR ON TITENS_CAR.ITEMPR_ID = TCONFIG_ITENS.ITEMPR_ID AND TITENS_CAR.TCARAC_ID = TCARACTERISTICAS.ID
JOIN focco3i.TESTABELECIMENTOS ON TESTABELECIMENTOS.ID = TPEDIDOS_VENDA.EST_ID_ENTR
JOIN focco3i.TCIDADES TCIDADES2 ON TCIDADES2.ID = TESTABELECIMENTOS.CID_ID
JOIN focco3i.TUFS TUFS2 ON TUFS2.ID = TCIDADES2.UF_ID
JOIN focco3i.TPAISES TPAISES2 ON TPAISES2.ID = TUFS2.PAIS_ID
JOIN focco3i.TIDIOMAS ON TIDIOMAS.ID = TPAISES2.IDIOMAS_ID
LEFT JOIN focco3i.TIDIOMAS TIDIOMAS_VAR ON TIDIOMAS_VAR.DESCRICAO = 'ETIQUETA_' || COALESCE(:idioma,TIDIOMAS.DESCRICAO)
LEFT JOIN focco3i.TVARIAVEIS_IDIOMAS ON TVARIAVEIS_IDIOMAS.TVAR_ID = TVARIAVEIS.ID AND TVARIAVEIS_IDIOMAS.IDIOMAS_ID = TIDIOMAS_VAR.ID


WHERE (SELECT LISTAGG(COALESCE(TVARIAVEIS_IDIOMAS2.DESCRICAO,TVARIAVEIS2.DESCRICAO)) WITHIN GROUP (ORDER BY COALESCE(TVARIAVEIS_IDIOMAS2.DESCRICAO,TVARIAVEIS2.DESCRICAO))
FROM focco3i.TCONFIG_ITENS TCONFIG_ITENS2
JOIN focco3i.TCARACTERISTICAS TCARACTERISTICAS2 ON TCARACTERISTICAS2.ID = TCONFIG_ITENS2.TCARAC_ID AND TCARACTERISTICAS2.TCONJ_ID NOT IN (963,980)
JOIN focco3i.TVARIAVEIS TVARIAVEIS2 ON TVARIAVEIS2.ID = TCONFIG_ITENS2.TVAR_ID
LEFT JOIN focco3i.TVARIAVEIS_IDIOMAS TVARIAVEIS_IDIOMAS2 ON TVARIAVEIS_IDIOMAS2.TVAR_ID = TVARIAVEIS2.ID AND TVARIAVEIS_IDIOMAS2.IDIOMAS_ID = TIDIOMAS_VAR.ID
JOIN focco3i.TITENS_CAR TITENS_CAR2 ON TITENS_CAR2.ITEMPR_ID = TCONFIG_ITENS2.ITEMPR_ID AND TITENS_CAR2.TCARAC_ID = TCARACTERISTICAS2.ID
WHERE TCONFIG_ITENS2.TMASC_ITEM_ID = TCONFIG_ITENS.TMASC_ITEM_ID 
AND TITENS_CAR2.TITEM_CAR_ID = TITENS_CAR.ID) IS NOT NULL
AND TPEDIDOS_VENDA.TIPO = :tipo_ped
AND TPEDIDOS_VENDA.NUM_PEDIDO = :pedido
) X