SELECT
TEMPRESAS.RAZAO_SOCIAL "rem_razao",
REGEXP_REPLACE(LPAD(0||TEMPRESAS.CNPJ, 14),'([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})','\1.\2.\3/\4-') "rem_cnpj",
REGEXP_REPLACE(TEMPRESAS.CEP, '([0-9]{5})([0-9]{3})', '\1-\2') "rem_cep",
TEMPRESAS.ENDERECO "rem_endereco",
TCIDADES.CIDADE || CASE WHEN TUFS.UF = 'EX' THEN NULL ELSE '/' || TUFS.UF END || ' - ' || TPAISES.DESCRICAO "rem_cidade",

TESTABELECIMENTOS.DESCRICAO "dest_razao",
CASE WHEN TESTABELECIMENTOS.CNPJ IS NOT NULL
THEN COALESCE(REGEXP_REPLACE(LPAD(TESTABELECIMENTOS.CNPJ, 14),'([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})','\1.\2.\3/\4-'),TESTABELECIMENTOS.DOC_ESTRANGEIRO)
ELSE COALESCE(REGEXP_REPLACE(LPAD(TESTABELECIMENTOS.CPF, 14),'([0-9]{3})([0-9]{3})([0-9]{3})([0-9]{2})','\1.\2.\3-\4'),TESTABELECIMENTOS.DOC_ESTRANGEIRO)
END "dest_cnpj",
COALESCE(REGEXP_REPLACE(TESTABELECIMENTOS.CEP, '([0-9]{5})([0-9]{3})', '\1-\2'),TESTABELECIMENTOS.COMPLEMENTO)"dest_cep",
TESTABELECIMENTOS.ENDERECO "dest_endereco",
TCIDADES2.CIDADE || CASE WHEN TUFS2.UF = 'EX' THEN NULL ELSE '/' || TUFS2.UF END || ' - ' || TPAISES2.DESCRICAO "dest_cidade",

COALESCE(:idioma,TIDIOMAS.DESCRICAO) "idioma",
TFORNECEDORES.DESCRICAO "transportadora",
TPEDIDOS_VENDA.NUM_PEDIDO "num_ped",
TITENS_PDV.ID "itpdv_id",
TITENS_PDV.NUM_ITEM "num_item",
TMARCAS_PROD.DESCRICAO "marca",
UPPER(TITENS_ENGENHARIA_ESP.TIPO_DE_CONFORTO) "conforto",
TRIM(
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TITENS.DESC_TECNICA
,'  ',''),'MODELO',''),'COMPOSE',''),'MESA',''),'APARADOR',''),'CAMA',''),'ESTANTE',''),'BIOMBO',''),'BANCO',''),'AVULSA',''),'E/',''),'PLUS','')
) "item",
TMASC_ITEM.ID "id",

(SELECT LISTAGG('<b>' || COALESCE(TCARAC_IDIOMAS.DESCRICAO,TCARACTERISTICAS.DESCRICAO) || ': </b> ' || COALESCE(COALESCE(COALESCE(TVARIAVEIS_IDIOMAS.DESCRICAO,TVARIAVEIS.DESCRICAO),TCONFIG_ITENS.TEXTO),CAST(TCONFIG_ITENS.VALOR AS VARCHAR2(100))), '<br>') 
WITHIN GROUP (ORDER BY TCONFIG_ITENS.SEQ) FROM focco3i.TCONFIG_ITENS 
LEFT JOIN focco3i.TCARACTERISTICAS ON TCARACTERISTICAS.ID = TCONFIG_ITENS.TCARAC_ID 
LEFT JOIN focco3i.TCARAC_IDIOMAS ON TCARAC_IDIOMAS.TCARAC_ID = TCARACTERISTICAS.ID AND TCARAC_IDIOMAS.IDIOMAS_ID = TIDIOMAS_CAR.ID 
LEFT JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID 
LEFT JOIN focco3i.TVARIAVEIS_IDIOMAS ON TVARIAVEIS_IDIOMAS.TVAR_ID = TVARIAVEIS.ID AND TVARIAVEIS_IDIOMAS.IDIOMAS_ID = TIDIOMAS_VAR.ID 
WHERE TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID AND TCONFIG_ITENS.SIT_CAR NOT IN (8,9)) "desc_masc",

(SELECT TVARIAVEIS.MNEMONICO FROM focco3i.TCONFIG_ITENS JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID WHERE TCONFIG_ITENS.TCARAC_ID = 1604 AND TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID)  "modulacao",
(SELECT COALESCE(TVARIAVEIS_IDIOMAS.DESCRICAO,TVARIAVEIS.DESCRICAO) FROM focco3i.TCONFIG_ITENS JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID LEFT JOIN focco3i.TVARIAVEIS_IDIOMAS ON TVARIAVEIS_IDIOMAS.TVAR_ID = TVARIAVEIS.ID AND TVARIAVEIS_IDIOMAS.IDIOMAS_ID = TIDIOMAS_VAR.ID WHERE TCONFIG_ITENS.TCARAC_ID = 1604 AND TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID) "desc_mod",
(SELECT TVARIAVEIS.MNEMONICO FROM focco3i.TCONFIG_ITENS JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID WHERE TCONFIG_ITENS.TCARAC_ID = 1606 AND TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID) "lado",
(SELECT TVARIAVEIS.MNEMONICO FROM focco3i.TCONFIG_ITENS JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID WHERE TCONFIG_ITENS.TCARAC_ID = 1624 AND TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID) "comprimento",
(SELECT TVARIAVEIS.MNEMONICO FROM focco3i.TCONFIG_ITENS JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID WHERE TCONFIG_ITENS.TCARAC_ID = 1744 AND TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID) "profundidade",
COALESCE(
(SELECT TVARIAVEIS.MNEMONICO FROM focco3i.TCONFIG_ITENS JOIN focco3i.TVARIAVEIS ON TVARIAVEIS.ID = TCONFIG_ITENS.TVAR_ID WHERE TCONFIG_ITENS.TCARAC_ID = 1924 AND TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID),
(SELECT TO_CHAR(SH_CUBAGEM_ALT.ALTURA,'FM999G999G990D00') || 'M' FROM otimiza.SH_CUBAGEM_ALT WHERE SH_CUBAGEM_ALT.ITEMPR_ID = TITENS_EMPR.ID AND SH_CUBAGEM_ALT.MOD_ID = (SELECT TCONFIG_ITENS.TVAR_ID FROM focco3i.TCONFIG_ITENS WHERE TCONFIG_ITENS.TCARAC_ID = 1604 AND TCONFIG_ITENS.TMASC_ITEM_ID = TMASC_ITEM.ID)) 
)"altura",

ROUND(1/NVL(TITENS_COM_CONF.FAT_CONV_VOL,TITENS_COMERCIAL.FAT_CONV_VOL),0) "volume",
ROUND(NVL(NVL(TITENS_ENG_CONF.PESO_BRT,TITENS_ENGENHARIA.PESO_BRT),0),1) "peso_bruto",
ROUND(NVL(NVL(TITENS_ENG_CONF.CUBAGEM,TITENS_ENGENHARIA.CUBAGEM),0),3) "cubagem",
(SELECT CAST(CAST(TNFS_SAIDA.NUM_NF AS INT) AS VARCHAR2(40)) FROM focco3i.TNFS_SAIDA JOIN focco3i.TITENS_NFS ON TITENS_NFS.NFS_ID = TNFS_SAIDA.ID WHERE TITENS_NFS.ID = (SELECT MAX(THIST_MOV_ITE_PDV.ITNFS_ID) FROM focco3i.THIST_MOV_ITE_PDV WHERE THIST_MOV_ITE_PDV.ITPDV_ID = TITENS_PDV.ID)) "nota"
FROM focco3i.TITENS_PDV

JOIN focco3i.TPEDIDOS_VENDA ON TPEDIDOS_VENDA.ID = TITENS_PDV.PDV_ID
JOIN focco3i.TFORNECEDORES ON TFORNECEDORES.ID = TPEDIDOS_VENDA.FORN_ID
JOIN focco3i.TESTABELECIMENTOS ON TESTABELECIMENTOS.ID = TPEDIDOS_VENDA.EST_ID_ENTR
JOIN focco3i.TEMPRESAS ON TEMPRESAS.ID = TPEDIDOS_VENDA.EMPR_ID
JOIN focco3i.TCIDADES ON TCIDADES.ID = TEMPRESAS.CID_ID
JOIN focco3i.TUFS ON TUFS.ID = TCIDADES.UF_ID
JOIN focco3i.TPAISES ON TPAISES.ID = TUFS.PAIS_ID
JOIN focco3i.TCLIENTES ON TCLIENTES.ID = TESTABELECIMENTOS.CLI_ID
JOIN focco3i.TCIDADES TCIDADES2 ON TCIDADES2.ID = TESTABELECIMENTOS.CID_ID
JOIN focco3i.TUFS TUFS2 ON TUFS2.ID = TCIDADES2.UF_ID
JOIN focco3i.TPAISES TPAISES2 ON TPAISES2.ID = TUFS2.PAIS_ID
JOIN focco3i.TIDIOMAS ON TIDIOMAS.ID = TPAISES2.IDIOMAS_ID
JOIN focco3i.TITENS_COMERCIAL ON TITENS_COMERCIAL.ID = TITENS_PDV.ITCM_ID
JOIN focco3i.TITENS_EMPR ON TITENS_EMPR.ID = TITENS_COMERCIAL.ITEMPR_ID
JOIN focco3i.TITENS ON TITENS.ID = TITENS_EMPR.ITEM_ID
JOIN focco3i.TITENS_ENGENHARIA ON TITENS_ENGENHARIA.ITEMPR_ID = TITENS_EMPR.ID
LEFT JOIN focco3i.TITENS_IMAGENS ON TITENS_IMAGENS.ITEM_ID = TITENS.ID
LEFT JOIN focco3i.TMASC_ITEM ON TMASC_ITEM.ID = TITENS_PDV.TMASC_ITEM_ID
LEFT JOIN focco3i.TITENS_COM_CONF ON TITENS_COM_CONF.TMASC_ITEM_ID = TMASC_ITEM.ID
LEFT JOIN focco3i.TITENS_ENG_CONF ON TITENS_ENG_CONF.TMASC_ITEM_ID = TMASC_ITEM.ID
LEFT JOIN focco3i.TITENS_ENGENHARIA_ESP ON TITENS_ENGENHARIA_ESP.ESPECIAL_ID = TITENS_ENGENHARIA.ID
LEFT JOIN focco3i.TMARCAS_PROD ON TMARCAS_PROD.ID = TITENS.MARCA_ID
LEFT JOIN focco3i.TIDIOMAS TIDIOMAS_CAR ON TIDIOMAS_CAR.DESCRICAO = 'ETIQUETA_' || COALESCE(:idioma,TIDIOMAS.DESCRICAO)
LEFT JOIN focco3i.TIDIOMAS TIDIOMAS_VAR ON TIDIOMAS_VAR.DESCRICAO = 'ETIQUETA_' || COALESCE(:idioma,TIDIOMAS.DESCRICAO)

WHERE TEMPRESAS.COD_EMP = 1
-- AND TITENS_IMAGENS.IMAGEM IS NOT NULL
AND NVL(TITENS_COM_CONF.FAT_CONV_VOL,TITENS_COMERCIAL.FAT_CONV_VOL) <> 0
AND TPEDIDOS_VENDA.TIPO = :tipo_ped
AND TPEDIDOS_VENDA.NUM_PEDIDO = :pedido